#!/bin/sh

################################################
#
# Double start check
#
################################################
function doubleCheck(){
    local checkitem="$0"
    local let procCnt=$(ps -A --format='%p%P%C%x%a' --width 2048 -w --sort pid \
                | grep "$checkitem" \
                | grep -v grep \
                | grep -v " -c sh " \
                | grep -v "$$" \
                | grep -c sh \
                | awk '{printf("%d",$1)}'
    )
    if [[ ${procCnt} -gt 0 ]];then
        echo -e "\033[;32m$(basename $0)\033[0m" "is running, this operation will be suspended"
        exit 1;
    fi
}

doubleCheck