#!/bin/bash

# 从github的库中获取最新版本的releases

PUBLISHER=$1
REPOSITORY=$2

URL="https://github.com/${PUBLISHER}/${REPOSITORY}/releases/latest"

VERSION=$(curl -sS ${URL} | sed -r 's/.*tag\/(.*)\".*/\1/g')

echo ${REPOSITORY}: ${VERSION}