#!/bin/bash


cecho(){
    KEYS=$1
    shift
    ECHOCMD="echo"
    [[ ${KEYS:0:1} == '0' ]] && ECHOCMD=$ECHOCMD" -n "
    read EFFECT FONTCOLOR BACKCOLOR <<< "${KEYS:1:1} ${KEYS:2:1} ${KEYS:3:1}"
    ${ECHOCMD} -e "\033[${EFFECT};4${BACKCOLOR};3${FONTCOLOR}m$@\033[0m"
}


usage(){
    cat <<< """Usage:
    $(basename $0) -f {hosts_file} [dir|files]
    示例: 
        $(basename $0) -f hosts_list test_file
        $(basename $0) root@192.168.100.101 test_file
    
    注意: 
        1. 未指定目标节点文件位置时使用本地文件绝对路径
        2. 确保目标节点目录存在
        3. 不指定目标用户时使用当前本地执行用户

    -q, --quiet         不显示消息
    -h, --help          帮助信息
    -d, --delete        删除远程节点不存在于本地的多余文件
    -f, --hosts_file    连接多个节点时的节点列表文件
    -i, --identity_file 连接时使用的ssh密钥文件
    -p, --password      连接时使用的密码(需要sshpass)
    -t, --timeout       超时时间
    """
    cecho 1019 $@
    exit 1
}


xsync(){

    [[ $(which rsync >& /dev/null) ]] || usage "$0 error: module 'rsync' not found"

    local TEMP=$(getopt -o qhdf:i:w:p:t: --long quiet,help,delete,hosts_file:,identity_file:,password:,port:,timeout: -n 'error' -- "$@")
    [[ $? != 0 ]] && usage "Terminating..." >&2 
    # 参数重排
    eval set -- "$TEMP"
    local RSY_PARS
    local SSh_PARS
    local HOSTLIST
    local PASSWD
    local SSH_PORT
    # 参数定义
    while true ; do
        case "$1" in
            -q|--quiet)         RSY_PARS+=" -q"; 
                shift 1 ;;
            -h|--help)          usage; 
                shift 1 ;;
            -d|--delete)        RSY_PARS+=" --delete"; 
                shift 1 ;;
            -f|--hosts_file)
                [[ -z $2 && -f $2 ]] && usage "$0 error: Specify the file for Parameter '-f | --hosts_file'.";
                HOSTLIST=$2;
                shift 2 ;;
            -i|--identity_file)
                [[ -z $2 && -f $2 ]] && usage "$0 error: Specify the identity file for Parameter '-i | --identity_file'.";
                SSh_PARS+=" -i $2";
                shift 2 ;;
            -w|--password)
                [[ $(which sshpass >& /dev/null) ]] || usage "$0 error: Parameter '-w | --password' requires the 'sshpass' module to be used, but this module was not found.";
                PASSWD="$2";
                shift 2 ;;
            -p|--port)
                [[ -z $2 && -f $2 ]] || usage "$0 error: Specify the SSH transport port for parameter '-p | --port'.";
                SSH_PORT="$2";
                shift 2 ;;
            -t|--timeout)       RSY_PARS+=" --timeout=$2";
                shift 2 ;;
            --) shift ; break ;;
            *) usage "Internal error!" ;;
        esac
    done
    # 检查需要同步的文件是否存在
    [[ -z $1 ]] && usage "$0 error: Please specify the file to be synchronized"
    [[ ! -f $1 && ! -d $1 ]] && usage "$0 error: cannot access $1: No such file or directory"
    local FILE=$(readlink -e $1); shift

    # 检查需要同步的目标节点
    # ip正则
    local REG='^((2(5[0-5]|[0-4][0-9]))|[0-1]?[0-9]{1,2})(\.((2(5[0-5]|[0-4][0-9]))|[0-1]?[0-9]{1,2})){3}$'
    
    # 执行来自文件的目标
    while read line
    do
        echo $line
    done < $HOSTLIST
    # 执行来自命令行的目标
    local TARGET=$2
    TARGET=(${TARGET//:/ })
    local HOST=${TARGET[0]}
    local FILEPATH=${TARGET[1]:=${FILE}}

    echo RSY_PARS:       $RSY_PARS
    echo SSh_PARS:       $SSh_PARS
    echo HOSTLIST:       $HOSTLIST
    echo PASSWD:         $PASSWD
    # rsync -azcP -e "ssh" test root@192.168.100.102:~

    # 生产随机md5值 md5sum <<< $RANDOM$RANDOM$RANDOM
    # uuid cat /proc/sys/kernel/random/uuid
    # awk -v RS="[\n@]+" '$0!~/(^$|#)|(^ |\t$)/{print $0}' <<< "$TEXT@$(cat 222 123 333 2> /dev/null)" | \
    # while read line
    # do
    #     let count++
    #     echo ${count}: $line
    # done

}
