#!/bin/bash -e 


############################################################################################################
#
# 初始化
#
############################################################################################################
function init(){
    # docker的下载连接
    DOCKER_DOWNLOAD_URL='https://download.docker.com/linux/static/stable/x86_64' # 末尾不带'/'
    # 在/tmp下创建临时目录
    TEMP_DIR=$(mktemp -d /tmp/$(basename $0).XXXXXX)
}


############################################################################################################
#
# 当前用户检查
#
############################################################################################################
function whoai(){


}



############################################################################################################
#
# 安装
#
############################################################################################################
function install_docker(){
    DOCKER_VERSION=$1
    curl -C - -o ${TEMP_DIR}/docker-20.10.7.tgz ${DOCKER_DOWNLOAD_URL}/${DOCKER_VERSION} # -C - 自动断点续传
    tar zxf ${DOCKER_VERSION} -C ${TEMP_DIR}
    cp ${TEMP_DIR}/docker/* /usr/bin/
}


case $1 in
    list )      # 显示docker官网现有版本列表
        echo "开始从${DOCKER_DOWNLOAD_URL}读取列表..."
        echo $(curl ${DOCKER_DOWNLOAD_URL}) | grep -Po "docker.*?tgz" | uniq | grep -Ev "ce|rootless"
        ;;
    install )   # 安装
        if [[ $# == 1 ]];then
        # 只有install一个参数时,本地安装最新版本
            TEMP_DIR=$(mktemp -d /tmp/$(basename $0).XXXXXX)
            echo 12312 $TEMP_DIR
            echo 111
        elif [[ $# == 2 ]];then
        # install后跟随版本号时安装指定版本
            echo 222
        else
        # 部署多节点
            echo 333
        fi
        ;;
    * )         # 未定义的参数
        echo xxx
        ;;
esac








