#!/bin/bash

function ssed(){
    usage(){
        echo "Usage: ssed <key> <value> <file>"
        echo $@
        exit 1
    }

    local KEY=$1
    local VALUE=$2
    local FILE=$3

    [[ ! -z ${KEY}   ]] && usage "Please specify a key"
    [[ ! -z ${VALUE} ]] && usage "Please specify a value"
    [[ ! -f ${FILE}  ]] && usage "$(basename $0): cannot access ${FILE}: No such file or directory"
    [[ ! -r ${FILE}  ]] && usage "$(basename $0): can't read ${FILE}: Permission denied"

    grep -q "^${KEY}" ${FILE} && sed -i "s/^${KEY}.*/${KEY}=${VALUE}/" ${FILE} || echo "${KEY}=${VALUE}" >> ${FILE}
}

ssed $@
