#!/bin/bash

usage(){
    cat <<< """Usage:
    $(basename $0) <key> <value> <file>

    -r, --reverse    使key在后,value在前(类似hosts文件)
    -d, --delimiter  key和value的连接符, 默认为'='
    """
}

# 参数收集
TEMP=$(getopt -o hrd:  --long help,reverse,delimiter: -n 'error' -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; fi
# 参数重排
eval set -- "$TEMP"
# 参数定义
while true ; do
    case "$1" in
        -h|--help)       usage          ; exit 0 ;;
        -r|--reverse)    REVERSE=1      ; shift 1 ;;
        -d|--delimiter)  DELIMITER=$2   ; shift 2 ;;
        --) shift ; break ;;
        *) usage; echo "Internal error!"; exit 1 ;;
    esac
done

KEY=$1
VALUE=$2
FILE=$3
DELIMITER=${DELIMITER:='='}
[[ -z ${REVERSE} ]] && FLAG="^${KEY}.*" || FLAG=".*${KEY}\s*$"
[[ ! -z ${REVERSE} ]] && read VALUE KEY <<< "${KEY} ${VALUE}"

STR="${KEY}${DELIMITER}${VALUE}"

[[ ! -f ${FILE}  ]] && touch ${FILE}
[[ ! -r ${FILE}  ]] && echo "$(basename $0): can't read ${FILE}: Permission denied" && exit 1

grep -q ${FLAG} ${FILE} && sed -i "s/${FLAG}/${STR}/" ${FILE} || echo "${STR}" >> ${FILE}