#!/bin/bash


cecho(){
    KEYS=$1
    shift
    ECHOCMD="echo"
    [[ ${KEYS:0:1} == '0' ]] && ECHOCMD=$ECHOCMD" -n "
    read EFFECT FONTCOLOR BACKCOLOR <<< "${KEYS:1:1} ${KEYS:2:1} ${KEYS:3:1}"
    ${ECHOCMD} -e "\033[${EFFECT};4${BACKCOLOR};3${FONTCOLOR}m$@\033[0m"
}


usage(){
    cat <<< """Usage:
    $(basename $0) -f {hosts_file} [dir|files]
    示例: 
        $(basename $0) -f hosts_list test_file
        $(basename $0) root@192.168.100.101 test_file
    
    注意: 
        1. 未指定目标节点文件位置时使用本地文件绝对路径
        2. 确保目标节点目录存在
        3. 不指定目标用户时使用当前本地执行用户

    -q, --quiet         不显示消息
    -h, --help          帮助信息
    -d, --delete        删除远程节点不存在于本地的多余文件
    -f, --hosts_file    连接多个节点时的节点列表文件
    -i, --identity_file 连接时使用的ssh密钥文件
    -p, --password      连接时使用的密码(需要sshpass)
    -t, --timeout       超时时间
    """
    cecho 1019 $@
    exit 1
}

check_env(){
    for m in $@
    do
        [[ $(which ${m} >& /dev/null) ]] || usage "$0 error: module ${m} not found"
    done    
}

add_repos(){
tee /etc/yum.repos.d/CentOS-infra.repo <<-'EOF'
[infra]
name=CentOS-$releasever - infra - mirrors.tuna.tsinghua.edu.cn
failovermethod=priority
baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos/7.9.2009/infra/x86_64/infra-common
        https://mirrors.aliyun.com/centos/7.9.2009/infra/x86_64/infra-common
        https://download.fedoraproject.org/pub/epel/7/x86_64
gpgcheck=0
enabled=0
EOF
}




rm -rf temp.cache
{
    inotifywait -mrqe attrib,close_write,move,create,delete --format '%w %f %e' /opt/ | \
    while read LINE
    do
        echo $LINE
        # 通过循环写来避免sed操作会删除原始文件建立新文件导致文件地址变化使定向失效
        echo $LINE >> temp.cache
    done
} &
jobs -p > pid
while true
do
    UUID=$(cat /proc/sys/kernel/random/uuid)
    echo "${UUID}" >> temp.cache
    # 删除操作时同一个目录多个文件删除会触发多次对同一个父目录的同步
    sed -n '1,/${UUID}/p' temp.cache | awk '{list[$1]=$2}END{for(i in list){print i,list[i]}}' | \
    while read FILENAME EVENT
    do
        if [[ $EVENT =~ 'CREATE' ]] || [[ $EVENT =~ 'CLOSE_WRITE' ]] || [[ $EVENT =~ 'MOVED_TO' ]] ||  [[ $EVENT =~ 'ATTRIB' ]];then
            rsync -qca ${FILENAME} root@192.168.100.102:${FILENAME}
        fi
        if [[ $EVENT =~ 'DELETE' ]] || [[ $EVENT =~ 'MOVED_FROM' ]];then
            rsync -qca --delete $(dirname ${FILENAME})/ root@192.168.100.102:$(dirname ${FILENAME})/
        fi
    done
    sed -i '1,/${UUID}/d' temp.cache
    sleep 10
done
# grep 'inotifywait' /proc/*/comm | awk -F/ '{system("kill "$3)}'
CREATE|CLOSE_WRITE|MOVED_TO|ATTRIB
DELETE|MOVED_FROM


sed -n '1,/${UUID}/p' log | awk '{list[$1]=$2}END{for(i in list){print i,list[i]}}' | 
awk 'function dir(dirname $2){if($2~/CREATE|CLOSE_WRITE|MOVED_TO|ATTRIB/){CRE=$1" "CRE}if($2~/DELETE|MOVED_FROM/){DEL=$1" "DEL}}END{print CRE"\n"DEL}'


cat log | awk '$3!=""{list[$1$3]=$2}END{for(i in list){print i,list[i]}}'



sed -n '1,/${UUID}/p' log | \
# 将操作记录分类
cat log | \
awk '$3==""{next}
     $2~/CREATE|CLOSE_WRITE|MOVED_TO|ATTRIB/ && index(LIST["C "$1$3],$3)==0
        {LIST["C "$1$3]=LIST["C "$1$3]" "$3}
     $2~/DELETE|MOVED_FROM/ && index(LIST["D "$1$3],$3)==0
        {LIST["D "$1$3]=LIST["D "$1$3]" "$3}
     END{for(i in LIST){print i,LIST[i]}}' | \
while read ACT DIR FILE

sed -n '1,/${UUID}/p' log | awk '$3==""{next}
     $2~/CREATE|CLOSE_WRITE|MOVED_TO|ATTRIB/&&index(LIST["C "$1],$3)==0{LIST["C "$1$3]=LIST["C "$1$3]" "$3}
     $2~/DELETE|MOVED_FROM/&&index(LIST["C "$1],$3)==0{LIST["D "$1]=LIST["D "$1]" "$3}
     END{for(i in LIST){print i,LIST[i]}}'
     
      | \
awk '$2~/CREATE|CLOSE_WRITE|MOVED_TO|ATTRIB/{LIST="CRE "$1"\n"LIST}
     $2~/DELETE|MOVED_FROM/{LIST="DEL "$1"\n"LIST}
     END{print LIST}' | \
awk 'NR==1{}
     NR==2{}'


$2~/CREATE|CLOSE_WRITE|MOVED_TO|ATTRIB/{list["C"]=$1$3" "list["C"]}
MYFUNC(){
    echo MYFUNC: $@
}
MAIN(){

}
cat log | awk '$3==""{next}
$2~/DELETE|MOVED_FROM/{dl=dl" "$1$3}
$2~/CREATE|CLOSE_WRITE|MOVED_TO|ATTRIB/&&index(cl[$1],$3)==0{cl[$1]=$3" "cl[$1]}
END{print dl;for(i in cl){print i,cl[i]}}' | awk \
'function invoke(ACT,SRC,DEST){system("rsync -ac --rsync-path=\""ACT" && rsync\" "SRC" "DEST)}
NR==1&&$0!=""{invoke("rm -rf "$0,"","root@192.168.100.102:")}
NR>=2{invoke("mkdir -p "$1,$2,"root@192.168.100.102:"$1)}'




 /opt/321
/opt/44/ 22
/opt/33/22/11/00/ oo
/opt/ 44 333 321
/opt/44/22/11/00/ oo
/opt/44/22/ 11
/opt/44/22/11/ 00